"""Scaffolding text for `archforge-optimizer init` — the user-tunable config template.

Owns the ACTIVE defaults that become `.archforge/archforge.py` (the project's sole
source of ArchForge tunables, made by `init`) and the `.env.example` key template.

Two roles, one source:
  * `init` writes ``archforge_config_text()`` verbatim to ``.archforge/archforge.py`` →
    the user's tunables. It ships with **active sane values** so the CLI works
    immediately after `init`; the user edits a value to change behaviour.
  * Under the test runner, ``archforge.userconfig`` execs the SAME ``TEMPLATE``
    in-memory (no disk file) so the suite sees the sane defaults
    (e.g. ``Thresholds().tau == 0.05``) with zero per-test files.

The values here are ArchForge's sane defaults — keep them in sync with what the
package historically shipped. This module is pure data (string constants); it imports
nothing from `archforge` and never reads the live `.env`.
"""
from __future__ import annotations

# --------------------------------------------------------------------------- #
# the sane tunable defaults — the ONE place the values live
# --------------------------------------------------------------------------- #
# (name, active-value-as-assignment, one-line purpose). The assignment text is
# emitted verbatim into the generated file AND exec'd by the resolver, so it must be
# valid Python and carry the real sane value (note DEFAULT_MODELS / DEFAULT_SUB_RUBRICS
# are the full dicts, not `{}` — the resolver must resolve them without KeyError).

_DEFAULT_MODELS = (
    '{"anthropic": "claude-sonnet-5", "openai": "gpt-4o", '
    '"groq": "openai/gpt-oss-120b", "gemini": "gemini-2.5-flash"}'
)
_DEFAULT_SUB_RUBRICS = (
    '{"correctness": "Is the final answer factually correct and aligned with the task?", '
    '"completeness": "Does the answer address every part of the task?", '
    '"grounding": "Are the claims supported by the inputs/context, not invented?"}'
)

_FIELDS: tuple[tuple[str, str, str], ...] = (
    # --- LLM providers ---
    ("PROVIDER", '"gemini"',
     "LLM provider for the Architect + Judge (scripted|anthropic|openai|groq|gemini)"),
    ("DEFAULT_MODELS", _DEFAULT_MODELS,
     "per-provider default model id (edit the dict to change a provider's default)"),
    # --- optimization policy ---
    ("DEFAULT_TAU", "0.05", "τ promotion margin — keep a candidate iff it beats incumbent by >= τ"),
    ("DEFAULT_DELTA", "0.07", "δ regression floor (>= τ) — rollback trigger (E6/I3)"),
    ("DEFAULT_REPEATS", "1", "R: repeats per eval-suite task (higher = less variance, more cost)"),
    ("MAX_REPEATS", "3", "cap on adaptive R the engine may raise near ±τ"),
    ("DEFAULT_UNRUNNABLE_FRAC", "0.25", "ε — a candidate with > ε crashed-task fraction is dropped (E4)"),
    ("DEFAULT_PLATEAU_CYCLES", "5", "K — consecutive no-promotion cycles -> plateau (E8)"),
    ("DEFAULT_MAX_CYCLES", "20", "hard ceiling on P-E-C cycles per evolve-loop run"),
    # --- grader resilience ---
    ("DEFAULT_JUDGE_RETRIES", "2", "judge (LLM-as-judge) call retries on transient outage (E9)"),
    ("BACKOFF_CAP_SECONDS", "30.0", "exponential-backoff ceiling between judge retries (E9)"),
    # --- judge scoring ---
    ("DEFAULT_RUBRIC_ID", '"default-v1"', "rubric id the Judge scores against (E2/I5 — stay within a rubric)"),
    ("DEFAULT_SUB_RUBRICS", _DEFAULT_SUB_RUBRICS,
     "sub-rubric texts (dict) the default rubric scores against"),
    # --- environment / budget / storage ---
    ("DEFAULT_ROOT_DIR", '".archforge"', "run state directory (specs/attempts/traces) — resolved against cwd"),
    ("DEFAULT_ENV_FILE", '".env"', "project .env loaded for provider API keys (setdefault => real env wins)"),
    ("DEFAULT_MAX_TOKENS_TOTAL", "None", "whole-run token budget cap (E3); None = uncapped"),
    ("DEFAULT_MAX_TOKENS_PER_CYCLE", "None", "per-cycle token cap; abort mid-cycle if exceeded (E3); None = uncapped"),
)

# section break points in _FIELDS (for grouping the emitted file)
_BREAKS: dict[int, str] = {
    2: "# --- optimization policy ------------------------------------------------",
    9: "# --- grader resilience ---------------------------------------------------",
    11: "# --- judge scoring -------------------------------------------------------",
    13: "# --- environment / budget / storage --------------------------------------",
}

_HEADER = """\
# archforge.py — ArchForge user-tunable config (generated by `archforge-optimizer init`).
#
# This is the SOLE source of ArchForge's tunable defaults. It ships with SANE ACTIVE
# values (below) so the CLI works immediately after `init`; edit a value to change
# ArchForge's behaviour across CLI flags, RunnerConfig/EngineConfig/Thresholds
# defaults, and the Judge. ArchForge reads this at USE time (not import), so deleting
# the file returns the "run `archforge-optimizer init`" guard.
#
# Framework internals (provider roster, storage dirnames, hash lengths, PROG,
# VERSION, ...) are NOT tunable here — they live in the shipped archforge/config.py.
# Only the names below are read from this file.
#

# --- LLM providers -----------------------------------------------------------
"""

_FOOTER = """
# Tip: this file is ACTIVE as-is. Edit only what you want to change; an edited
# value takes effect on the next `archforge-optimizer` run.
"""


def archforge_config_text() -> str:
    """The full body of the generated `.archforge/archforge.py` (active sane defaults)."""
    lines = [_HEADER.rstrip("\n")]
    for i, (name, value, purpose) in enumerate(_FIELDS):
        if i in _BREAKS:
            lines.append("")
            lines.append(_BREAKS[i])
        lines.append(f"# {purpose}")
        lines.append(f"{name} = {value}")
    lines.append(_FOOTER.rstrip("\n"))
    return "\n".join(lines) + "\n"


# The active sane-default assignments, exec'd by archforge.userconfig under the test
# runner (so the suite sees sane defaults) — same string `init` writes to disk.
TEMPLATE: str = archforge_config_text()


def env_example_text() -> str:
    """The body of the generated `.env.example` (empty provider key var names)."""
    return (
        "# .env.example — copy to .env (gitignored) and fill in your keys.\n"
        "# ArchForge loads ./.env on startup (load_env) so a checked-out repo\n"
        "# with keys present 'just runs' for `archforge-optimizer evolve`. A real\n"
        "# env var or `--api-key` always overrides the file. NEVER commit .env.\n"
        "\n"
        "# ANTHROPIC_API_KEY=\n"
        "# OPENAI_API_KEY=\n"
        "# GROQ_API_KEY=\n"
        "# GEMINI_API_KEY=\n"
    )


# The tunable names — exported so callers/tests enumerate the editable surface.
EDITABLE_NAMES: tuple[str, ...] = tuple(name for name, _, _ in _FIELDS)

__all__ = ["archforge_config_text", "env_example_text", "TEMPLATE", "EDITABLE_NAMES"]
